services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  debug:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    privileged: true
    devices:
      - /dev/snd:/dev/snd
    environment:
      - GST_DEBUG_DUMP_DOT_DIR=/tmp/gstreamer-101
      - XDG_RUNTIME_DIR=/run/user/0
      - GST_DEBUG=3
