version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
  debug:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - .:/app
    devices:
      - /dev/snd:/dev/snd
